name: Build Kivy APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-11-jdk unzip wget
          python3 -m pip install --upgrade pip
          pip install buildozer cython kivy

      - name: Install Android SDK & Tools
        run: |
          # Define Android SDK path
          export ANDROID_SDK_ROOT=$HOME/.buildozer/android/platform/android-sdk
          export CMDLINE_TOOLS=$ANDROID_SDK_ROOT/cmdline-tools
          export LATEST=$CMDLINE_TOOLS/latest

          # Create required directories
          mkdir -p $LATEST

          # Download and install command-line tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
          unzip -q cmdline-tools.zip -d $CMDLINE_TOOLS
          mv $CMDLINE_TOOLS/cmdline-tools/* $LATEST/

          # Grant execute permissions
          chmod +x $LATEST/bin/sdkmanager

          # Add SDK tools to PATH
          echo "export PATH=$LATEST/bin:$ANDROID_SDK_ROOT/platform-tools:$ANDROID_SDK_ROOT/build-tools/33.0.2:$PATH" >> $HOME/.bashrc
          source $HOME/.bashrc

          # Accept SDK licenses
          yes | $LATEST/bin/sdkmanager --licenses || true

          # Install platform tools & build tools
          $LATEST/bin/sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.2" "ndk;25.2.9519653"

          # Verify sdkmanager exists
          if [ ! -f "$LATEST/bin/sdkmanager" ]; then
            echo "Error: 'sdkmanager' installation failed!"
            exit 1
          fi
          echo "✅ Android SDK and tools installed successfully."

      - name: Build APK
        run: |
          export ANDROID_HOME=$HOME/.buildozer/android/platform/android-sdk
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$ANDROID_HOME/build-tools/33.0.2:$PATH
          buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: MyApp
          path: bin/*.apk
