name: Build Kivy APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libmtdev1 libgl1-mesa-dev mesa-utils \
            build-essential python3 python3-pip openjdk-11-jdk unzip wget \
            lib32z1 lib32stdc++6 aidl
          python -m pip install --upgrade pip
          pip install buildozer cython kivy

      - name: Install Android SDK and Tools
        run: |
          # Set up environment variables
          export ANDROID_SDK_ROOT=$HOME/.buildozer/android/platform/android-sdk
          export CMDLINE_TOOLS=$ANDROID_SDK_ROOT/cmdline-tools
          export LATEST=$CMDLINE_TOOLS/latest
          mkdir -p $LATEST

          # Download and extract command-line tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
          unzip -o cmdline-tools.zip -d $CMDLINE_TOOLS
          mv $CMDLINE_TOOLS/cmdline-tools/* $LATEST/

          # Add tools to PATH
          echo "export PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/platform-tools:$ANDROID_SDK_ROOT/build-tools/33.0.2:$PATH" >> $HOME/.bashrc
          source $HOME/.bashrc

          # Accept SDK licenses
          yes | $LATEST/bin/sdkmanager --licenses || true

          # Install required tools
          $LATEST/bin/sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.2" "ndk;25.2.9519653"

          # Verify installation
          if [ ! -f "$LATEST/bin/sdkmanager" ]; then
            echo "Error: 'sdkmanager' installation failed!"
            exit 1
          fi
          echo "Android SDK and tools installed successfully."

      - name: Install and Configure Aidl
        run: |
          # Ensure aidl is installed and copied correctly
          mkdir -p ~/.buildozer/android/platform/android-sdk/build-tools/31.0.0
          cp /usr/bin/aidl ~/.buildozer/android/platform/android-sdk/build-tools/31.0.0/
          chmod 777 ~/.buildozer/android/platform/android-sdk/build-tools/31.0.0/aidl

          # Validate aidl installation
          if [ ! -f ~/.buildozer/android/platform/android-sdk/build-tools/31.0.0/aidl ]; then
            echo "Error: 'aidl' was not copied successfully."
            exit 1
          fi
          echo "'aidl' installed and configured successfully."

      - name: Build APK
        run: |
          export ANDROID_HOME=$HOME/.buildozer/android/platform/android-sdk
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$ANDROID_HOME/build-tools/33.0.2:$PATH
          buildozer init
          buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: MyApp
          path: bin/*.apk
